spring:
  application:
    name: upload
logging:
  level:
    org:
      apache:
        coyote:
          http11: # debug
file:
  dir: /Users/hanjeongsoo/coding/study/Lecture-SpringMVC-2/upload/file/