spring:
  application:
    name: exception
  web:
    error:
      whitelabel:
        enabled: false
      include-exception: true
      include-message: always
      include-stacktrace: always
      include-binding-errors: always